[tool.poetry]
name = "poetry-plugin-bundle"
version = "0.1.0"
description = "Poetry plugin to bundle projects into various formats"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "poetry_plugin_bundle", from = "src" }
]

include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.2.0rc1"

[tool.poetry.dev-dependencies]
poetry = {git = "https://github.com/python-poetry/poetry.git"}
pre-commit = "^2.6"
pytest = "^6.2.3"
pytest-mock = "^3.6.1"
mypy = ">=0.950"

[tool.poetry.plugins."poetry.application.plugin"]
export = "poetry_plugin_bundle.plugin:BundleApplicationPlugin"

[tool.black]
target-version = ['py37']
preview = true

[tool.isort]
py_version = 37
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
strict = true
enable_error_code = ["ignore-without-code"]
files = ["src", "tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
