[tool.poetry]
name = "poetry-plugin-bundle"
version = "1.0.0"
description = "Poetry plugin to bundle projects into various formats"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "poetry_plugin_bundle", from = "src" }
]

include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.2.0rc1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.6"
pytest = "^7.1.2"
pytest-mock = "^3.6.1"
mypy = ">=0.950"

[tool.poetry.plugins."poetry.application.plugin"]
export = "poetry_plugin_bundle.plugin:BundleApplicationPlugin"

[tool.black]
target-version = ['py37']
preview = true

[tool.isort]
py_version = 37
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2

[tool.mypy]
enable_error_code = [
    "ignore-without-code",
    "redundant-expr",
    "truthy-bool",
]
explicit_package_bases = true
files = ["src", "tests"]
mypy_path = "src"
namespace_packages = true
show_error_codes = true
strict = true

[[tool.mypy.overrides]]
module = [
  'cleo.*',
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
